### ISSUE TITLE
#1 Building complete architecture  for Anonymous Message Board

### ISSUE THREAD

**Issue by compozite-research** [compozite-research/anonymous-board#1]
# Description
This project aims to build an anonymous message board for researchers to internally discuss on topics without being traced.
The requirements are the following:
1. A centralized entity sends a link to each user to participate in the message board
2. The members click on the link to create keys on a blockchain
3. The centralized entity cannot trace the blockchain keys to a particular individual
4. Any external member clicking on the link  can successfully get in the message board without any alerts but the message he posts will be flagged
5. Any internal member can do the same as 4. 
6. Centralized  entity can add new members securely
7. Any internal members can add new members securely.
8. keeping the posts in IPFS
9. Checking integrity  of each post with Merkle Tree

# Tasks

- [x] Schema for setup phase
- [x] Schema for message board
- [x] Schema for adding new members by centralized entity
- [x] Schema for adding new members by each member
- [x]  Add how each member can be regonised with the organisation using Verifiable credentials
- [x] Modify the setup phase with verifiable credentials
- [x] Do a write up and loom video

**Comment by compozite-research** [comment]
New suggestions by the team, added tasks
